from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1c71e3dcf717"
down_revision = "314601ce7660"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sub_categoria", sa.String(length=100), nullable=True)
        )
        batch_op.add_column(sa.Column("variante", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("codigo_barras", sa.String(length=50), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_dim_producto_codigo_barras"), ["codigo_barras"], unique=False
        )

    tipo_doc_enum = sa.Enum(
        "CARGA_INICIAL",
        "FACTURA",
        "GUIA_REMISION",
        "BOLETA",
        "NOTA_CREDITO",
        "AJUSTE_INVENTARIO",
        name="tipo_documento_enum",
    )
    tipo_doc_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table("fact_movimiento", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tipo_documento", tipo_doc_enum, nullable=False))
        batch_op.add_column(
            sa.Column("numero_documento", sa.String(length=100), nullable=False)
        )
        batch_op.create_check_constraint(
            "check_signo_cantidad_tipo",
            "((tipo_movimiento IN ('ENTRADA_COMPRA', 'AJUSTE_POSITIVO')) AND cantidad > 0) OR "
            "((tipo_movimiento IN ('SALIDA_VENTA', 'AJUSTE_NEGATIVO')) AND cantidad < 0) OR "
            "(tipo_movimiento = 'TRANSFERENCIA')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fact_movimiento", schema=None) as batch_op:
        batch_op.drop_column("numero_documento")
        batch_op.drop_column("tipo_documento")

    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_producto_codigo_barras"))
        batch_op.drop_column("codigo_barras")
        batch_op.drop_column("variante")
        batch_op.drop_column("sub_categoria")

    # ### end Alembic commands ###
