from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "314601ce7660"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_almacen",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("ubicacion", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dim_producto",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("nombre", sa.String(length=200), nullable=False),
        sa.Column("categoria", sa.String(length=100), nullable=False),
        sa.Column("marca", sa.String(length=100), nullable=False),
        sa.Column(
            "precio_venta_actual", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_producto_categoria"), ["categoria"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dim_producto_marca"), ["marca"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dim_producto_sku"), ["sku"], unique=True)

    op.create_table(
        "dim_usuario",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nombres", sa.String(length=100), nullable=False),
        sa.Column("apellidos", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dim_usuario", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dim_usuario_email"), ["email"], unique=True
        )

    op.create_table(
        "fact_movimiento",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("almacen_id", sa.Uuid(), nullable=False),
        sa.Column("usuario_id", sa.Uuid(), nullable=False),
        sa.Column(
            "tipo_movimiento",
            sa.Enum(
                "ENTRADA_COMPRA",
                "SALIDA_VENTA",
                "AJUSTE_POSITIVO",
                "AJUSTE_NEGATIVO",
                "TRANSFERENCIA",
                name="tipo_movimiento_enum",
            ),
            nullable=False,
        ),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("costo_unitario", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("moneda", sa.String(length=3), nullable=False),
        sa.Column("tipo_cambio", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("saldo_cantidad", sa.Integer(), nullable=False),
        sa.Column("numero_serie", sa.String(length=100), nullable=True),
        sa.Column("fecha_movimiento", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cantidad != 0", name="check_cantidad_no_cero"),
        sa.CheckConstraint("costo_unitario >= 0", name="check_costo_no_negativo"),
        sa.ForeignKeyConstraint(
            ["almacen_id"],
            ["dim_almacen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["dim_producto.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["dim_usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fact_movimiento", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fact_movimiento_almacen_id"), ["almacen_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fact_movimiento_fecha_movimiento"),
            ["fecha_movimiento"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fact_movimiento_producto_id"), ["producto_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fact_movimiento_usuario_id"), ["usuario_id"], unique=False
        )

    op.create_table(
        "fact_stock_almacen",
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("almacen_id", sa.Uuid(), nullable=False),
        sa.Column("stock_actual", sa.Integer(), nullable=False),
        sa.Column("costo_promedio", sa.Numeric(precision=15, scale=4), nullable=False),
        sa.Column("ultima_actualizacion", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("stock_actual >= 0", name="check_stock_no_negativo"),
        sa.ForeignKeyConstraint(
            ["almacen_id"],
            ["dim_almacen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["dim_producto.id"],
        ),
        sa.PrimaryKeyConstraint("producto_id", "almacen_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_stock_almacen")
    with op.batch_alter_table("fact_movimiento", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fact_movimiento_usuario_id"))
        batch_op.drop_index(batch_op.f("ix_fact_movimiento_producto_id"))
        batch_op.drop_index(batch_op.f("ix_fact_movimiento_fecha_movimiento"))
        batch_op.drop_index(batch_op.f("ix_fact_movimiento_almacen_id"))

    op.drop_table("fact_movimiento")
    with op.batch_alter_table("dim_usuario", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_usuario_email"))

    op.drop_table("dim_usuario")
    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dim_producto_sku"))
        batch_op.drop_index(batch_op.f("ix_dim_producto_marca"))
        batch_op.drop_index(batch_op.f("ix_dim_producto_categoria"))

    op.drop_table("dim_producto")
    op.drop_table("dim_almacen")
    # ### end Alembic commands ###
    sa.Enum(name="tipo_movimiento_enum").drop(op.get_bind(), checkfirst=True)
