from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "50181cd99d14"
down_revision = "1c71e3dcf717"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "precio_compra_actual",
                sa.Numeric(precision=10, scale=2),
                server_default="0.00",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dim_producto", schema=None) as batch_op:
        batch_op.drop_column("precio_compra_actual")

    # ### end Alembic commands ###
