from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9f2a5ac675f3"
down_revision = "a3f2c9d4e8b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guia_remision",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("numero_guia", sa.String(length=20), nullable=False),
        sa.Column("fecha_emision", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_traslado", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "motivo_traslado",
            sa.Enum(
                "COMPRA",
                "VENTA",
                "TRASLADO_ENTRE_ESTABLECIMIENTOS",
                "DEVOLUCION",
                "OTROS",
                name="motivo_traslado_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "estado",
            sa.Enum(
                "BORRADOR",
                "EN_TRANSITO",
                "RECIBIDO",
                "ANULADO",
                name="estado_guia_enum",
            ),
            nullable=False,
        ),
        sa.Column("almacen_origen_id", sa.Uuid(), nullable=False),
        sa.Column("almacen_destino_id", sa.Uuid(), nullable=False),
        sa.Column("usuario_creador_id", sa.Uuid(), nullable=False),
        sa.Column(
            "peso_bruto_total", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("conductor_nombre", sa.String(length=100), nullable=True),
        sa.Column("conductor_dni", sa.String(length=20), nullable=True),
        sa.Column("vehiculo_placa", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["almacen_destino_id"],
            ["dim_almacen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["almacen_origen_id"],
            ["dim_almacen.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_creador_id"],
            ["dim_usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guia_remision", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guia_remision_almacen_destino_id"),
            ["almacen_destino_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_guia_remision_almacen_origen_id"),
            ["almacen_origen_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_guia_remision_numero_guia"), ["numero_guia"], unique=True
        )

    op.create_table(
        "guia_remision_detalle",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("guia_remision_id", sa.Uuid(), nullable=False),
        sa.Column("producto_id", sa.Uuid(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "costo_unitario_origen", sa.Numeric(precision=15, scale=4), nullable=False
        ),
        sa.CheckConstraint("cantidad > 0", name="check_guia_cantidad_positiva"),
        sa.CheckConstraint(
            "costo_unitario_origen >= 0", name="check_guia_costo_no_negativo"
        ),
        sa.ForeignKeyConstraint(
            ["guia_remision_id"],
            ["guia_remision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producto_id"],
            ["dim_producto.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("guia_remision_detalle", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_guia_remision_detalle_guia_remision_id"),
            ["guia_remision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_guia_remision_detalle_producto_id"),
            ["producto_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guia_remision_detalle", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guia_remision_detalle_producto_id"))
        batch_op.drop_index(batch_op.f("ix_guia_remision_detalle_guia_remision_id"))

    op.drop_table("guia_remision_detalle")
    with op.batch_alter_table("guia_remision", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_guia_remision_numero_guia"))
        batch_op.drop_index(batch_op.f("ix_guia_remision_almacen_origen_id"))
        batch_op.drop_index(batch_op.f("ix_guia_remision_almacen_destino_id"))

    op.drop_table("guia_remision")
    op.execute("DROP TYPE IF EXISTS estado_guia_enum")
    op.execute("DROP TYPE IF EXISTS motivo_traslado_enum")
    # ### end Alembic commands ###
